spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:13306/tradingview?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 5000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000
      use-global-data-source-stat: true
      filter: stat,wall,slf4j
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: LEGACYHTML5
  redis:
    port: 16379
    host: 127.0.0.1
    password: tyronekucao
    lettuce:
      pool:
        max-idle: 10   # 最大空闲连接
        min-idle: 0   # 最小空闲链接
        max-active: 200 # 最大连接数（负数表示没有限制）
        max-wait: -1   # 最大阻塞等待时间（负数表示没有限制）
    timeout: 3000     # 链接超时时间（毫秒）
    database: 0
  #字符编码
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    basename: i18n/messages,i18n/validationMessages
    encoding: utf-8
#activeMQ
activemq:
  brokerUrl: tcp://127.0.0.1:61616
  inMemory: true  #是否是内存模式
  password: tyrone_kucao
  user: tyrone
  useExponentialBackOff: true  # 是否在每次尝试重新发送失败后,增长这个等待时间
  maximumRedeliveries: 1        # 重发次数,默认为6次   这里设置为10次
  initialRedeliveryDelay: 1     # 重发时间间隔,默认为1秒
  backOffMultiplier: 2          # 第一次失败后重新发送之前等待500毫秒,第二次失败再等待500 * 2毫秒,这里的2就是value
  useCollisionAvoidance: false  # 是否避免消息碰撞
  maximumRedeliveryDelay: -1    # 设置重发最大拖延时间-1 表示没有拖延只有use-collision-avoidance(true)为true时生效
  poolMaxConnections: 5 #连接池最大连接数
  poolIdleTimeout: 30000 #空闲的链接过去时间
  poolExpiryTimeout: 0  #强制的链接过期时间
websocket:
  port: 8083
  host: 0.0.0.0
fdfs:
  so-timeout: 1500
  connect-timeout: 2000
  pool:
    max-total: 100
    max-wait-millis: 5000
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 47.75.96.126:22122
  web-server-url: http://47.75.96.126/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.liuqi.business.model

#pagehelper 配置
pagehelper:
  helperDialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
#日志级别
logging:
   config: classpath:logback.xml
   level:
      com:
         liuqi:
           business:
             mapper: error
server:
  port: 8081

aliyunpic:
  endpoint: https://oss-cn-hongkong.aliyuncs.com
  accessKeyId: LTAI4GD5W4ETWsej9D28aZyD
  accessKeySecret: brj0ugBPx9krrtA7Xpfie6KKelMRpT
  accessRequestUrl: https://luqiyun.oss-cn-hongkong.aliyuncs.com

udun:
  callback: http://192.168.0.110:8081


